export type OutboxStatus="erro_retry"|"enviado"|"falha_permanente"|"cancelado";
export const MAX_EMAIL_ATTEMPTS=5;
const retryMinutes:Record<number,number>={1:1,2:5,3:15,4:60};
export function retryAt(attempts:number,now=new Date()):string|null{const minutes=retryMinutes[attempts];return minutes?new Date(now.getTime()+minutes*60_000).toISOString():null;}
export function sanitizeEmailError(value:unknown):string{return(value instanceof Error?value.message:String(value??"Falha desconhecida")).replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g,"[email]").replace(/(?:Bearer\s+)?[A-Za-z0-9_-]{24,}/gi,"[redacted]").replace(/[\r\n\t]+/g," ").slice(0,500);}
export function validEmail(value:unknown):value is string{return typeof value==="string"&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());}
const escapeHtml=(value:unknown)=>String(value??"").replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]!);
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(`${value.slice(0,10)}T12:00:00-03:00`)):null;
export type ApprovalTemplateData={approverName:string;traveler:string|null;requester:string|null;origin:string|null;destination:string|null;outboundDate:string|null;returnDate:string|null;link:string};
export function approvalPendingHtml(data:ApprovalTemplateData):string{const fields=[["Viajante",data.traveler],["Solicitante",data.requester],["Origem",data.origin],["Destino",data.destination],["Data de ida",date(data.outboundDate)],["Data de retorno",date(data.returnDate)]].filter((entry):entry is[string,string]=>Boolean(entry[1]));return `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#1f2937"><p>Olá, ${escapeHtml(data.approverName)}.</p><p>Existe uma solicitação de passagem aguardando sua aprovação.</p><table>${fields.map(([label,value])=>`<tr><td style="padding:4px 12px 4px 0"><strong>${escapeHtml(label)}</strong></td><td>${escapeHtml(value)}</td></tr>`).join("")}</table><p style="margin:24px 0"><a href="${escapeHtml(data.link)}" style="background:#163d6b;color:#fff;padding:12px 18px;text-decoration:none;border-radius:4px">ABRIR SOLICITAÇÃO</a></p><p>TanksBR — Portal de Passagens</p></body></html>`;}
export type ApprovalResultTemplateData={requesterName:string;traveler:string|null;reason:string|null;origin:string|null;destination:string|null;outboundDate:string|null;link:string;result:"aprovada"|"reprovada"};
export function resolveTravelerName(manual:string|null|undefined,privateName:string|null|undefined,employeeName:string|null|undefined):string|null{return manual?.trim()||privateName?.trim()||employeeName?.trim()||null;}
export function approvalResultHtml(data:ApprovalResultTemplateData):string{const approved=data.result==="aprovada";const fields=[["Viajante",data.traveler],...(approved?[["Motivo",data.reason] as[string,string|null]]:[]),["Origem",data.origin],["Destino",data.destination],["Data da viagem",date(data.outboundDate)]].filter((entry):entry is[string,string]=>Boolean(entry[1]));const message=approved?"Sua solicitação de passagem foi aprovada.":"Sua solicitação de passagem não foi aprovada.";const guidance=approved?"":"<p>Consulte o motivo e os detalhes no Portal de Passagens.</p>";return `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#1f2937"><p>Olá, ${escapeHtml(data.requesterName)}.</p><p>${message}</p>${guidance}<table>${fields.map(([label,value])=>`<tr><td style="padding:4px 12px 4px 0"><strong>${escapeHtml(label)}</strong></td><td>${escapeHtml(value)}</td></tr>`).join("")}</table><p style="margin:24px 0"><a href="${escapeHtml(data.link)}" style="background:#163d6b;color:#fff;padding:12px 18px;text-decoration:none;border-radius:4px">ABRIR SOLICITAÇÃO</a></p><p>TanksBR — Portal de Passagens</p></body></html>`;}
export type OperationalRejectionTemplateData={requesterName:string;traveler:string|null;reason:string|null;origin:string|null;destination:string|null;outboundDate:string|null;link:string};
export function operationalRejectionHtml(data:OperationalRejectionTemplateData):string{const fields=[["Viajante",data.traveler],["Motivo da viagem",data.reason],["Origem",data.origin],["Destino",data.destination],["Data da viagem",date(data.outboundDate)]].filter((entry):entry is[string,string]=>Boolean(entry[1]));return `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#1f2937"><p>Olá, ${escapeHtml(data.requesterName)}.</p><p>Sua solicitação de passagem foi recusada pela equipe responsável pela operação de passagens.</p><p>Consulte o motivo e os detalhes no Portal de Passagens.</p><table>${fields.map(([label,value])=>`<tr><td style="padding:4px 12px 4px 0"><strong>${escapeHtml(label)}</strong></td><td>${escapeHtml(value)}</td></tr>`).join("")}</table><p style="margin:24px 0"><a href="${escapeHtml(data.link)}" style="background:#163d6b;color:#fff;padding:12px 18px;text-decoration:none;border-radius:4px">ABRIR SOLICITAÇÃO</a></p><p>TanksBR — Portal de Passagens</p></body></html>`;}
