import assert from "node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";
import{compraFolgaLiberada,dataAntecipaCiclo,folgaFuturaBloqueia,justificativaAntecipacaoValida,SEM_HISTORICO_FOLGA,type CicloFolga}from"../src/folgaCampoRules.ts";
const sql=readFileSync(new URL("../supabase/migrations/202608050003_controle_ciclo_folga_campo.sql",import.meta.url),"utf8"),dry=readFileSync(new URL("../supabase/manual/DRY_RUN_202608050003_controle_ciclo_folga_campo.sql",import.meta.url),"utf8"),page=readFileSync(new URL("../src/pages.tsx",import.meta.url),"utf8"),verify=readFileSync(new URL("../supabase/manual/verificar_controle_ciclo_folga_campo.sql",import.meta.url),"utf8"),smoke=readFileSync(new URL("../supabase/manual/smoke_controle_ciclo_folga_campo.sql",import.meta.url),"utf8");
const ciclo=(p:Partial<CicloFolga>={}):CicloFolga=>({possui_historico:false,ultima_solicitacao_id:null,ultima_folga_realizada:null,ultima_data_prevista_ciclo:null,proxima_folga_prevista:null,data_limite_recomendada:null,solicitacao_futura_existente_id:null,solicitacao_futura_data:null,solicitacao_futura_status:null,...p});
test("mensagem sem histórico é exata",()=>assert.match(SEM_HISTORICO_FOLGA,/Não há registro de folga de campo anterior/));
test("10/06 + 90 = 08/09",()=>{const d=new Date("2026-06-10T12:00:00Z");d.setUTCDate(d.getUTCDate()+90);assert.equal(d.toISOString().slice(0,10),"2026-09-08")});
test("08/09 + 90 = 07/12",()=>{const d=new Date("2026-09-08T12:00:00Z");d.setUTCDate(d.getUTCDate()+90);assert.equal(d.toISOString().slice(0,10),"2026-12-07")});
test("atraso não muda âncora",()=>assert.match(sql,/coalesce\(v_ultima\.folga_data_prevista_ciclo,v_ultima\.data_ida\)\+90/));
test("antecipação é detectada",()=>assert.equal(dataAntecipaCiclo("2026-09-01","2026-09-08"),true));
test("data igual não antecipa",()=>assert.equal(dataAntecipaCiclo("2026-09-08","2026-09-08"),false));
test("justificativa usa trim e 10 caracteres",()=>{assert.equal(justificativaAntecipacaoValida(" 123456789 "),false);assert.equal(justificativaAntecipacaoValida(" 1234567890 "),true)});
test("pendente bloqueia compra",()=>assert.equal(compraFolgaLiberada("pendente"),false));
test("aprovada libera compra",()=>assert.equal(compraFolgaLiberada("aprovada"),true));
test("futura existente bloqueia",()=>assert.equal(folgaFuturaBloqueia(ciclo({solicitacao_futura_existente_id:"x"})),true));
test("recusada e cancelada não constam nos bloqueadores",()=>assert.match(sql,/status in \('solicitada','em_andamento','passagem_comprada'\)/));
test("somente finalizada realizada alimenta ciclo",()=>assert.match(sql,/s\.status='finalizada' and s\.data_ida<=/));
test("bloco aparece somente em folga campo",()=>assert.match(page,/form\.motivo==="folga_campo"&&form\.funcionario_id/));
test("seleção consulta ciclo",()=>assert.match(page,/ro_obter_ciclo_folga_funcionario/));
test("bloco mostra três datas",()=>{assert.match(page,/Última folga de campo/);assert.match(page,/Próxima folga prevista/);assert.match(page,/Data recomendada para solicitar/)});
test("troca limpa ciclo e justificativa",()=>{assert.match(page,/setCicloFolga\(null\)/);assert.match(page,/folga_antecipacao_justificativa:""/)});
test("duplicidade é verificada no submit e banco",()=>{assert.match(page,/folgaFuturaBloqueia/);assert.match(sql,/FOLGA_FUTURA_DUPLICADA/);assert.match(sql,/pg_advisory_xact_lock/)});
test("antecipação mantém regra de prazo separada",()=>{assert.match(page,/form\.data_ida < dataMinimaInput/);assert.match(page,/Justificativa da antecipação/);assert.match(page,/Justificativa da exceção/)});
test("aprovação exige RO ativo",()=>assert.match(sql,/ro_aprovar_antecipacao_folga[\s\S]*ro_is_operador_ativo\(auth\.uid\(\)\)/));
test("gerente e diretor não aprovam por role",()=>assert.doesNotMatch(sql,/ro_aprovar_antecipacao_folga[\s\S]*?\bgerente\b|ro_aprovar_antecipacao_folga[\s\S]*?\bdiretor\b/));
test("RO vê aprovação via canOperateRO",()=>assert.match(page,/access\.canOperateRO&&row\.folga_antecipacao_status==="pendente"/));
test("compra UI fica oculta pendente",()=>assert.match(page,/compraFolgaLiberada\(row\.folga_antecipacao_status\)/));
test("compra banco bloqueia solicitação custo anexo e storage",()=>{assert.match(sql,/ANTECIPACAO_FOLGA_PENDENTE/);assert.match(sql,/ro_bloquear_custo_folga_pendente/);assert.match(sql,/ro_bloquear_anexo_folga_pendente/);assert.match(sql,/ro_storage_insert/)});
test("edição invalida aprovação",()=>assert.match(sql,/aprovacao_antecipacao_invalidada/));
test("recusa existente é complementada",()=>{assert.match(sql,/create or replace function public\.ro_recusar_solicitacao/);assert.match(sql,/folga_antecipacao_status:='recusada'/)});
test("prefill não copia controle de ciclo",()=>assert.doesNotMatch(sql,/ro_obter_dados_para_refazer_solicitacao/));
test("migration é transacional e sem massa histórica",()=>{assert.match(sql,/^begin;/i);assert.match(sql,/commit;\s*$/i);assert.doesNotMatch(sql,/truncate|delete\s+from\s+public\.ro_passagem_solicitacoes/i)});
test("migration depende da recusa",()=>{assert.match(sql,/ro_is_operador_ativo/);assert.match(sql,/ro_solicitacao_foi_comprada/);assert.match(sql,/recusada/)});
test("dry run sincronizado",()=>{const n=(v:string)=>v.replace(/(?:commit|rollback);\s*$/i,"END;").replace(/\s+/g," ").trim();assert.equal(n(sql),n(dry))});
test("verificação é somente leitura",()=>assert.doesNotMatch(verify,/\b(insert|update|delete|truncate|alter|drop|create)\b/i));
test("smoke usa rollback",()=>{assert.match(smoke,/^begin;/i);assert.match(smoke,/rollback;\s*$/i)});
test("sem tela ou relatório novo",()=>{assert.doesNotMatch(page,/Controle de folgas/);assert.doesNotMatch(page,/Relatório de folgas/) });
test("funções protegidas revogam public e anon",()=>assert.match(sql,/revoke all on function[\s\S]*from public,anon/));
