import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const sql=readFileSync(new URL("../supabase/migrations/202608040001_regras_prazos_rh_desligamentos.sql",import.meta.url),"utf8");
const dry=readFileSync(new URL("../supabase/manual/DRY_RUN_202608040001_regras_prazos_rh_desligamentos.sql",import.meta.url),"utf8");
test("migration é transacional",()=>{assert.match(sql,/\bbegin;[\s\S]*commit;\s*$/i);});
test("migration não contém mutações históricas em massa",()=>{assert.doesNotMatch(sql,/\b(delete\s+from|truncate\s+|drop\s+table)\s+public\.ro_passagem_solicitacoes/i);});
test("não contém service_role ou bucket público",()=>{assert.doesNotMatch(sql,/service_role/i);assert.match(sql,/values\('ro-documentos-internos','ro-documentos-internos',false/i);});
test("não cadastra RH ou feriados",()=>{assert.doesNotMatch(sql,/insert\s+into\s+public\.ro_rh_responsaveis\s*\(/i);assert.doesNotMatch(sql,/insert\s+into\s+public\.ro_calendario_nao_util\s*\(/i);});
test("administração usa auth.uid e e-mail case-insensitive",()=>{assert.match(sql,/ro_can_manage_rh\(\)[\s\S]*u\.id=auth\.uid\(\)[\s\S]*lower\(u\.email\)=lower\('fernanda\.souza@tanksbr\.com\.br'\)/i);});
test("insert e updates relevantes possuem triggers",()=>{assert.match(sql,/before insert on public\.ro_passagem_solicitacoes/i);assert.match(sql,/before update of motivo,desligamento_subtipo,data_ida,primeiro_embarque_em,origem,destino/i);});
test("RPC valida objeto real, ownership compatível, mime e tamanho",()=>{assert.match(sql,/storage\.objects[\s\S]*owner_id::text=auth\.uid\(\)::text/i);assert.match(sql,/metadata->>'mimetype'/i);assert.match(sql,/metadata->>'size'/i);});
test("limpeza órfã possui policy DELETE sem permitir apagar vinculado",()=>{assert.match(sql,/for delete to authenticated[\s\S]*owner_id::text=auth\.uid\(\)::text[\s\S]*not exists\(select 1 from public\.ro_passagem_documentos_internos/i);});
test("RH não recebe custos e RO permanece pela função existente",()=>{assert.match(sql,/ro_child_cost_select[\s\S]*using\(public\.ro_can_view_all\(\)\)/i);assert.doesNotMatch(sql,/create or replace function public\.ro_can_operate/i);});
test("funções definer têm search_path e EXECUTE revogado",()=>{const definers=[...sql.matchAll(/create or replace function ([^(]+)\([^$]+?security definer set search_path=/gi)];assert.ok(definers.length>=8);assert.match(sql,/revoke all on function[\s\S]*ro_validar_nova_solicitacao\(\)/i);});
test("viagem diretoria é histórica e rejeitada na criação",()=>{assert.match(sql,/motivo is null or motivo in \([^)]*'viagem_diretoria'/i);assert.match(sql,/new\.motivo='viagem_diretoria' then raise exception 'MOTIVO_NAO_DISPONIVEL'/i);});
test("compatibilidade histórica usa constraint NOT VALID",()=>assert.match(sql,/ro_desligamento_subtipo_ck[\s\S]*\) not valid;/i));
test("edição preserva origem histórica e registra revalidação",()=>{assert.match(sql,/else new\.origem_solicitacao:=old\.origem_solicitacao/i);assert.match(sql,/solicitacao_revalidada/i);});
test("role nula falha fechada por booleano explícito",()=>{assert.match(sql,/v_is_gerencial boolean:=coalesce\(v_role,''\) in \('gerente','diretor'\)/i);assert.doesNotMatch(sql,/v_role not in \('gerente','diretor'\)/i);});
test("motivo null exige autorização administrativa existente",()=>{assert.match(sql,/v_can_administrativo boolean:=coalesce\(public\.ro_can_view_all\(\),false\)/i);assert.match(sql,/new\.motivo is null and not v_can_administrativo/i);});
test("owner_id sempre é comparado como texto",()=>{assert.equal((sql.match(/owner_id::text=auth\.uid\(\)::text/gi)||[]).length,3);assert.doesNotMatch(sql,/owner_id\s*=\s*auth\.uid\(\)/i);});
test("calendário invalida old e new e audita conjunto de anos",()=>{assert.match(sql,/v_ano_antigo[\s\S]*old\.data/i);assert.match(sql,/v_ano_novo[\s\S]*new\.data/i);assert.match(sql,/anos_invalidados/i);assert.match(sql,/v_ano_antigo=v_ano_novo then v_anos:=array\[v_ano_novo\]/i);});
test("insert direto e RPC passam pela proteção de motivo null",()=>{assert.match(sql,/before insert on public\.ro_passagem_solicitacoes[\s\S]*ro_validar_nova_solicitacao/i);assert.match(sql,/ro_criar_solicitacao_validada[\s\S]*insert into public\.ro_passagem_solicitacoes/i);});
test("DRY RUN começa com BEGIN e termina com ROLLBACK",()=>{assert.match(dry,/^\s*(?:--[^\n]*\n)*begin;/i);assert.match(dry,/ROLLBACK;\s*$/i);assert.doesNotMatch(dry,/commit;\s*$/i);});
test("DRY RUN contém as correções críticas da fonte",()=>{for(const pattern of [/v_is_gerencial boolean:=coalesce/i,/MOTIVO_ADMINISTRATIVO_NAO_PERMITIDO/i,/owner_id::text=auth\.uid\(\)::text/i,/anos_invalidados/i]){assert.match(sql,pattern);assert.match(dry,pattern);}});
test("DRY RUN replica integralmente a migration, trocando apenas COMMIT por ROLLBACK",()=>{const normalize=(value:string)=>value.replace(/^\uFEFF/,"").replace(/--[^\n]*/g,"").replace(/(?:commit|rollback);\s*$/i,"END;").replace(/\s+/g," ").trim();assert.equal(normalize(dry),normalize(sql));});
test("campos nulos críticos falham fechados",()=>{assert.match(sql,/solicitante_id is distinct from auth\.uid\(\)/i);assert.match(sql,/desligamento_subtipo is null or coalesce\(new\.desligamento_subtipo,''\) not in/i);assert.match(sql,/v_primeiro is null then raise exception 'PRIMEIRO_EMBARQUE_OBRIGATORIO'/i);});
