import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const sql=fs.readFileSync("supabase/migrations/202608210001_pacote_1_aprovadores_individuais_denise.sql","utf8");
const page=fs.readFileSync("src/pages.tsx","utf8");
const app=fs.readFileSync("src/App.tsx","utf8");
const diagnostic=fs.readFileSync("supabase/manual/diagnostico_pacote_1_aprovacoes_denise.sql","utf8");

test("aprovador individual e Minhas aprovações usam vínculo explícito",()=>{assert.match(sql,/aprovador_id=auth\.uid\(\)/);assert.match(sql,/v\.aprovador_id is distinct from auth\.uid\(\)/);assert.match(page,/approvalsOnly[\s\S]*\.eq\("aprovador_id", userId\)/);assert.match(page,/approvalView === "pending"[\s\S]*\.eq\("aprovacao_status", "pendente"\)[\s\S]*\.in\("aprovacao_status", \["aprovada", "reprovada"\]\)/);assert.match(app,/\/minhas-aprovacoes/);});
test("criação direta não contorna a RPC canônica",()=>{assert.match(sql,/CRIACAO_SOMENTE_POR_RPC_COM_APROVADOR/);assert.match(sql,/create trigger ro_exigir_fluxo_aprovacao_nova\s+before insert/);assert.match(sql,/set_config\(\s*'ro\.approval_creation',\s*'1',\s*true\s*\)[\s\S]*ro_criar_solicitacao_colaborador_validada/);});
test("coordenadores, Higor e Flávio são candidatos por role ou UUID",()=>{assert.match(sql,/role::text='coordenador'/);assert.match(sql,/3660689c-1e6f-4e09-b414-3433b44d1681/);assert.match(sql,/0811a9c7-b52e-4213-9086-ffddefbbca16/);assert.doesNotMatch(sql,/higor cardoso|fl[aá]vio (?:psdovani )?sturion/i);});
test("autoaprovação é restrita ao próprio coordenador",()=>{assert.match(sql,/v_auto:=\s*v_aprovador=auth\.uid\(\)[\s\S]*role::text='coordenador'/);assert.match(sql,/AUTOAPROVACAO_NAO_PERMITIDA/);assert.match(sql,/Autoaprovação pelo próprio coordenador/);});
test("RH, RO, Gerência e Diretoria têm dispensa registrada",()=>{assert.match(sql,/ro_is_rh_active/);assert.match(sql,/ro_can_operate/);assert.match(sql,/gerente','diretor/);assert.match(sql,/Aprovação dispensada por regra de perfil/);});
test("reprovação exige motivo, elegibilidade, vínculo, estado e histórico",()=>{assert.match(sql,/MOTIVO_REPROVACAO_MINIMO_10_CARACTERES/);assert.match(sql,/v\.aprovador_id is distinct from auth\.uid\(\)/);assert.match(sql,/APROVADOR_NAO_ELEGIVEL/);assert.match(sql,/aprovacao_status='reprovada'/);assert.match(sql,/Solicitação reprovada pelo aprovador responsável\. Motivo:/);});
test("Denise é autorizada somente pelo UUID canônico",()=>{assert.match(sql,/d6081413-3730-41f0-981d-935a44303993/);assert.doesNotMatch(sql,/denise\.pires@|Denise Pires/i);assert.match(sql,/EDICAO_PASSAGEM_EXCLUSIVA_DENISE/);assert.match(sql,/PASSAGEM_COMPLEMENTAR_EXCLUSIVA_DENISE/);});
test("edição de passagem exige justificativa e registra antes, depois, autor e data",()=>{assert.match(sql,/JUSTIFICATIVA_MINIMO_10_CARACTERES/);assert.match(sql,/Valor da passagem %s alterado de R\$ %s para R\$ %s\. Justificativa: %s/);assert.match(sql,/jsonb_build_object\(\s*'custo_id'[\s\S]*'valor_anterior'[\s\S]*'valor_novo'[\s\S]*'alterado_por'[\s\S]*'alterado_em'/);assert.match(page,/ro_atualizar_valor_passagem/);});
test("custos genéricos excluem passagem e mantêm os quatro tipos operacionais",()=>{assert.match(fs.readFileSync("supabase/migrations/20260816173000_permite_editar_custos_operacionais_ro.sql","utf8"),/tipo not in \('hospedagem','uber','refeicao','outros'\)/);assert.match(page,/ro_atualizar_custo_operacional/);});
test("Pacote 1 mantém bloqueios de operação e filhos enquanto pendente",()=>{assert.match(sql,/SOLICITACAO_AGUARDANDO_APROVACAO/);assert.match(sql,/ro_custos_bloquear_sem_aprovacao/);assert.match(sql,/ro_anexos_bloquear_sem_aprovacao/);assert.match(sql,/approval_creation/);});
test("complementar usa segmento Storage exclusivo e associação atômica",()=>{assert.match(sql,/\[2\]='complementares'\s+and public\.ro_is_denise/);assert.match(sql,/STORAGE_PATH_COMPLEMENTAR_INVALIDO/);assert.match(sql,/insert into public\.ro_passagem_anexos[\s\S]*insert into public\.ro_passagem_historico/);assert.match(page,/complementar \? "\/complementares\/" : "\/"/);});
test("históricos permanecem sem default ou backfill de aprovação",()=>{assert.match(sql,/add column if not exists aprovacao_status text,/);assert.doesNotMatch(sql,/add column if not exists aprovacao_status text[^,;]*default/i);for(const update of sql.match(/update public\.ro_passagem_solicitacoes set[\s\S]*?;/gi)||[])assert.match(update,/\bwhere\b/i);});
test("diagnóstico do banco real é estritamente somente leitura",()=>{assert.doesNotMatch(diagnostic,/\b(insert|update|delete|merge|truncate|alter|create|drop|grant|revoke)\b/i);assert.match(diagnostic,/^-- SOMENTE LEITURA/);});
