import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {motivoPrefillPermitido,motivoRecusaValido,podeRecusarSolicitacao,solicitacaoFoiComprada,statusContaComoAberto} from "../src/recusaRules.ts";
import type {Solicitacao} from "../src/types.ts";

const row=(patch:Partial<Solicitacao>={})=>({status:"solicitada",comprado_em:null,comprado_por:null,custos:[],anexos:[],...patch}) as Solicitacao;
const page=readFileSync(new URL("../src/pages.tsx",import.meta.url),"utf8");
const app=readFileSync(new URL("../src/App.tsx",import.meta.url),"utf8");
const auto=readFileSync(new URL("../supabase/migrations/202607240001_auto_finalizacao_solicitacoes.sql",import.meta.url),"utf8");
const sql=readFileSync(new URL("../supabase/migrations/202608050002_recusa_solicitacao_ro.sql",import.meta.url),"utf8");
const dry=readFileSync(new URL("../supabase/manual/DRY_RUN_202608050002_recusa_solicitacao_ro.sql",import.meta.url),"utf8");
const verify=readFileSync(new URL("../supabase/manual/verificar_recusa_solicitacao_ro.sql",import.meta.url),"utf8");
const smoke=readFileSync(new URL("../supabase/manual/smoke_recusa_solicitacao_ro.sql",import.meta.url),"utf8");

test("RO ativo vê recusa",()=>assert.equal(podeRecusarSolicitacao(true,row()),true));
for(const nome of ["RO inativo","gerente sem RO","diretor sem RO","solicitante comum","RH sem RO"])test(`${nome} não vê recusa`,()=>assert.equal(podeRecusarSolicitacao(false,row()),false));
test("solicitação comprada não mostra recusa",()=>assert.equal(podeRecusarSolicitacao(true,row({status:"passagem_comprada"})),false));
test("compra por timestamp bloqueia recusa",()=>assert.equal(solicitacaoFoiComprada(row({comprado_em:"2026-08-05T12:00:00Z"})),true));
test("custo de passagem bloqueia recusa",()=>assert.equal(solicitacaoFoiComprada(row({custos:[{id:"1",tipo:"passagem",descricao:null,valor:1,centro_custo_id:null}]})),true));
test("anexo de passagem bloqueia recusa",()=>assert.equal(solicitacaoFoiComprada(row({anexos:[{} as never]})),true));
for(const status of ["finalizada","cancelada","recusada"] as const)test(`${status} não mostra recusa`,()=>assert.equal(podeRecusarSolicitacao(true,row({status})),false));
test("modal exige 10 caracteres úteis",()=>{assert.equal(motivoRecusaValido(" 123456789 "),false);assert.equal(motivoRecusaValido(" 1234567890 "),true);});
test("aviso informa ação definitiva",()=>assert.match(page,/Esta ação é definitiva\. O solicitante precisará criar uma nova solicitação/));
test("duplo clique é bloqueado por busy",()=>assert.match(page,/if\(busy\|\|!motivoRecusaValido\(util\)\)return/));
test("badge muda para Recusada",()=>assert.match(readFileSync(new URL("../src/lib.ts",import.meta.url),"utf8"),/recusada:'Recusada'/));
test("motivo aparece no detalhe",()=>assert.match(page,/t="Motivo" v=\{row\.motivo_recusa\}/));
test("notificação interna é única",()=>{assert.match(sql,/where not exists\(select 1 from public\.ro_passagem_notificacoes/i);assert.doesNotMatch(sql,/email|resend|whatsapp/i);});
test("recusada não é aberta nem atrasada",()=>assert.equal(statusContaComoAberto("recusada"),false));
test("botão refazer aparece ao solicitante original",()=>assert.match(page,/row\.status === "recusada" && row\.solicitante_id === userId/));
test("prefill copia somente campos permitidos",()=>{assert.match(sql,/jsonb_build_object\('solicitacao_origem_id'[\s\S]*'observacoes_solicitante'/i);assert.doesNotMatch(sql,/jsonb_build_object\([^;]*(storage_path|motivo_recusa|justificativa_excecao_prazo|comprado_por)/i);});
test("campos copiados permanecem editáveis",()=>assert.match(page,/setForm\(\(atual\)=>\(\{\.\.\.atual/));
test("documentos e custos não são copiados",()=>{const prefill=sql.slice(sql.indexOf("create or replace function public.ro_obter_dados_para_refazer_solicitacao"),sql.indexOf("create or replace function public.ro_auditar_solicitacao_refeita"));assert.doesNotMatch(prefill,/ro_passagem_(documentos|custos|anexos)/i);});
test("justificativa de exceção é limpa",()=>assert.match(page,/justificativa_excecao_prazo:""/));
test("motivo não permitido é limpo",()=>assert.equal(motivoPrefillPermitido("admissao",["ferias"]),""));
test("data copiada passa pela limpeza atual",()=>assert.match(page,/limparDataIdaInvalida\(atual\.data_ida, dataMinimaInput\)/));
test("solicitacao_origem_id é enviada",()=>assert.match(page,/solicitacao_origem_id:String\(prefill\.solicitacao_origem_id/));
test("status Recusada aparece no filtro",()=>assert.match(readFileSync(new URL("../src/lib.ts",import.meta.url),"utf8"),/value:'recusada',label:'Recusada'/));
test("auto-finalização continua exclusiva de compradas",()=>assert.match(auto,/where s\.status = 'passagem_comprada'/));
test("fluxo de compra válido permanece disponível",()=>assert.match(page,/\["em_analise", "em_andamento"\]\.includes\(row\.status\)/));
test("associação RO ativa não usa role",()=>{assert.match(sql,/from public\.ro_responsaveis r where r\.user_id=p_user and r\.ativo/);assert.doesNotMatch(sql,/ro_is_operador_ativo[\s\S]*?gerente|ro_is_operador_ativo[\s\S]*?diretor/i);});
test("auth uid é obrigatório e carimbos são internos",()=>{assert.match(sql,/if auth\.uid\(\) is null then raise exception 'NAO_AUTENTICADO'/);assert.match(sql,/recusada_em=now\(\),recusada_por=auth\.uid\(\)/);});
test("update direto não contorna RPC",()=>assert.match(sql,/RECUSA_SOMENTE_PELA_RPC/));
test("status recusada é terminal também para filhos",()=>{assert.match(sql,/old\.status='recusada' then raise exception 'SOLICITACAO_RECUSADA_IMUTAVEL'/);assert.match(sql,/ro_bloquear_custo_recusada/);assert.match(sql,/ro_bloquear_anexo_recusada/);});
test("prefill só pertence ao solicitante original",()=>assert.match(sql,/s\.solicitante_id=auth\.uid\(\) and s\.status='recusada'/));
test("vínculo é FK restritiva e não autorreferente",()=>{assert.match(sql,/solicitacao_origem_id uuid references public\.ro_passagem_solicitacoes\(id\) on delete restrict/);assert.match(sql,/solicitacao_origem_id<>id/);});
test("migration é transacional, idempotente e sem massa histórica",()=>{assert.match(sql,/^begin;/i);assert.match(sql,/commit;\s*$/i);assert.doesNotMatch(sql,/truncate|delete\s+from\s+public\.ro_passagem_solicitacoes/i);for(const update of sql.match(/update\s+public\.ro_passagem_solicitacoes[\s\S]*?;/gi)||[])assert.match(update,/\bwhere\b/i);});
test("dry run integral termina em rollback",()=>{const n=(v:string)=>v.replace(/(?:commit|rollback);\s*$/i,"END;").replace(/\s+/g," ").trim();assert.equal(n(sql),n(dry));assert.match(dry,/rollback;\s*$/i);});
test("grants públicos são revogados",()=>assert.match(sql,/revoke all on function[\s\S]*from public,anon/));
test("verificação é somente leitura",()=>assert.doesNotMatch(verify,/\b(insert|update|delete|truncate|alter|drop|create)\b/i));
test("smoke isolado começa BEGIN e termina ROLLBACK",()=>{assert.match(smoke,/^begin;/i);assert.match(smoke,/rollback;\s*$/i);});
test("App deriva operação da associação RO ativa",()=>assert.match(app,/\.from\("ro_responsaveis"\)[\s\S]*\.eq\("ativo", true\)[\s\S]*canOperateRO: isRO/));
