export type ComplementaryDraftDocument = { id:string; nome_arquivo:string; conteudo_sha256:string; tamanho_bytes:number; partida_em:string; valor:string|number; observacao:string };
const hex=(digest:ArrayBuffer)=>[...new Uint8Array(digest)].map((value)=>value.toString(16).padStart(2,"0")).join("");
export async function sha256BytesHex(blob:Blob){return hex(await crypto.subtle.digest("SHA-256",await blob.arrayBuffer()));}
export async function sha256TextHex(value:string){return hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));}
const money=(value:unknown)=>{if(value===null||value===undefined||value==="")return null;const parsed=Number(value);return Number.isFinite(parsed)?parsed.toFixed(2):String(value);};
export function complementaryGroupSignature(documents:Array<{id:string}>){return documents.map((item)=>item.id).sort().join("|");}
export function canonicalizeComplementaryDraft(input:{solicitacaoId:string;groups:Array<{documents:ComplementaryDraftDocument[]}>;centroCustoId:string;imprevisto:boolean;motivo:string;custosAdicionais:Array<Record<string,unknown>>}){
 return{solicitacao_id:input.solicitacaoId,complementares:input.groups.map((group)=>({signature:complementaryGroupSignature(group.documents),anexos:group.documents.map((item)=>({client_ref:item.id,nome_arquivo:item.nome_arquivo,tamanho_bytes:item.tamanho_bytes,conteudo_sha256:item.conteudo_sha256.toLowerCase(),partida_em:item.partida_em||null,valor:money(item.valor),observacao:item.observacao.trim()||null})).sort((a,b)=>a.client_ref.localeCompare(b.client_ref))})).sort((a,b)=>a.signature.localeCompare(b.signature)),centro_custo_id:input.centroCustoId,imprevisto:Boolean(input.imprevisto),motivo_complementar:input.motivo.trim().replace(/\s+/g," "),custos_adicionais:input.custosAdicionais.map((item)=>({tipo:String(item.tipo||""),descricao:String(item.descricao||"").trim()||null,valor:money(item.valor),centro_custo_id:String(item.centro_custo_id||"")})).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))};
}
