-- Somente leitura. Compare os totais históricos antes e depois da aplicação controlada.
select column_name,data_type,is_nullable from information_schema.columns where table_schema='public' and table_name='ro_passagem_solicitacoes' and column_name in ('recusada_em','recusada_por','motivo_recusa','solicitacao_origem_id') order by column_name;
select conname,pg_get_constraintdef(oid,true) definicao from pg_constraint where conrelid='public.ro_passagem_solicitacoes'::regclass and (conname in ('ro_status_valido','ro_recusa_consistencia','ro_solicitacao_origem_diferente') or contype='f' and pg_get_constraintdef(oid) ilike '%solicitacao_origem_id%') order by conname;
select p.proname,pg_get_function_identity_arguments(p.oid) argumentos,has_function_privilege('authenticated',p.oid,'EXECUTE') authenticated_executa,has_function_privilege('anon',p.oid,'EXECUTE') anon_executa from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('ro_is_operador_ativo','ro_solicitacao_foi_comprada','ro_recusar_solicitacao','ro_obter_dados_para_refazer_solicitacao','ro_proteger_recusa_terminal','ro_bloquear_filho_solicitacao_recusada') order by p.proname;
select event_object_table,trigger_name,event_manipulation,action_statement from information_schema.triggers where trigger_schema='public' and trigger_name in ('ro_proteger_recusa_terminal','ro_bloquear_custo_recusada','ro_bloquear_anexo_recusada','ro_auditar_solicitacao_refeita') order by trigger_name,event_manipulation;
select tablename,policyname,cmd,qual,with_check from pg_policies where schemaname in ('public','storage') and (tablename like 'ro_passagem_%' or tablename='objects') order by tablename,policyname;
select indexname,indexdef from pg_indexes where schemaname='public' and indexname in ('ro_solicitacoes_status_idx','ro_solicitacoes_recusada_por_idx','ro_solicitacoes_origem_idx') order by indexname;
select count(*) total_historico,count(*) filter(where status='recusada') recusadas,count(*) filter(where solicitacao_origem_id is not null) refeitas,min(created_at) mais_antiga,max(created_at) mais_recente from public.ro_passagem_solicitacoes;
select count(*) notificacoes_recusa from public.ro_passagem_notificacoes where canal='interno' and destinatario_tipo='solicitante' and mensagem='Sua solicitação foi recusada. Consulte o motivo no Portal e faça uma nova solicitação com os dados corrigidos.';
