-- Somente leitura.
select column_name,data_type,is_nullable from information_schema.columns where table_schema='public' and table_name='ro_passagem_solicitacoes' and column_name like 'folga_%' order by ordinal_position;
select conname,contype,pg_get_constraintdef(oid,true) definicao from pg_constraint where conrelid='public.ro_passagem_solicitacoes'::regclass and conname like 'ro_folga_%' order by conname;
select indexname,indexdef from pg_indexes where schemaname='public' and indexname like 'ro_folga_%' order by indexname;
select p.proname,pg_get_function_identity_arguments(p.oid) argumentos,has_function_privilege('authenticated',p.oid,'EXECUTE') autenticado,has_function_privilege('anon',p.oid,'EXECUTE') anon from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('ro_obter_ciclo_folga_funcionario','ro_funcionario_possui_folga_futura_ativa','ro_aprovar_antecipacao_folga','ro_validar_ciclo_folga_campo','ro_bloquear_compra_antecipacao_pendente') order by p.proname;
select trigger_name,event_manipulation,action_statement from information_schema.triggers where trigger_schema='public' and trigger_name like '%folga%' order by trigger_name,event_manipulation;
select tablename,policyname,cmd,qual,with_check from pg_policies where schemaname in ('public','storage') and (qual ilike '%folga_antecipacao%' or with_check ilike '%folga_antecipacao%');
select count(*) filter(where motivo='folga_campo' and folga_data_prevista_ciclo is not null) folgas_com_ciclo,count(*) filter(where motivo='folga_campo' and folga_ciclo_anterior_id is null) sem_historico,count(*) filter(where folga_antecipacao_status='pendente') pendentes,count(*) filter(where folga_antecipacao_status='aprovada') aprovadas,count(*) filter(where folga_antecipacao_status='recusada') recusadas,min(created_at) historico_mais_antigo,max(created_at) historico_mais_recente from public.ro_passagem_solicitacoes;
select funcionario_id,count(*) duplicidades_ativas from public.ro_passagem_solicitacoes where motivo='folga_campo' and data_ida>=(now() at time zone 'America/Sao_Paulo')::date and (status in ('solicitada','em_andamento','passagem_comprada') or folga_antecipacao_status in ('pendente','aprovada')) group by funcionario_id having count(*)>1;
